### ISSUE TITLE
Invalid project id

### ISSUE THREAD

**Issue by dfdgsdfg** [crowdin/vscode-crowdin#17]
Seems `crowdin.yml` configured correctly. CLI works well with it like listing or download.

Here is a log that is related on Log (Extension Host)

```
[2020-04-13 13:30:16.518] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/dididi/.vscode/extensions/ms-azuretools.vscode-docker-1.0.0/main
[2020-04-13 13:30:21.309] [exthost] [info] ExtensionService#_doActivateExtension Crowdin.vscode-crowdin {"startup":false,"extensionId":{"value":"Crowdin.vscode-crowdin","_lower":"crowdin.vscode-crowdin"},"activationEvent":"onView:tmsFiles"}
[2020-04-13 13:30:21.309] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/dididi/.vscode/extensions/crowdin.vscode-crowdin-1.0.3/dist/extension.js
[2020-04-13 13:30:21.470] [exthost] [info] ExtensionService#_doActivateExtension Orta.vscode-ios-common-files {"startup":true,"extensionId":{"value":"Orta.vscode-ios-common-files","_lower":"orta.vscode-ios-common-files"},"activationEvent":"workspaceContains:fastlane/Fastfile"}
```

**Comment by crowdin-support** [comment]
Hi @dfdgsdfg I'm sorry for the inconvenience! 

Let me forward it to our developers for further investigation, we will get back to you with the updates in the short run

**Comment by andrii-bodnar** [comment]
Hi @dfdgsdfg , could you please provide your `crowdin.yml` file content?

**Comment by dfdgsdfg** [comment]
Of course.

```yaml
"project_identifier": "________ from project settings > API ________ "
"api_key": "________ from project settings > API ________ "
"preserve_hierarchy": true

files: [
    {
      "source": "lib/l10n/*.arb",

      "translation": "lib/l10n/intl_%two_letters_code%.arb",
    },
  ]
```

**Comment by andrii-bodnar** [comment]
@dfdgsdfg this plugin works only with the new [Configuration File Config](https://support.crowdin.com/configuration-file-v3/) (for CLI v3).

All you need to do is:
- change `project_identifier` to `project_id`. Project ID can be found in the *Project Settings > API*.
- change `api_key` to `api_token`. API token must be generated in the *Account Settings > API & SSO*.

Also, we will try to fix the current behavior and display an appropriate error message.

**Comment by dfdgsdfg** [comment]
Still have same error

```yaml
"project_id": "__from Project Settings > API__"
"api_token": "__Account Settings > API & SSO > Personal Access Tokens__"
"base_path": ""
"preserve_hierarchy": true
``

**Comment by andrii-bodnar** [comment]
@dfdgsdfg, I suppose you are using CLI v2. This config (containing `project_id`, `api_token`) compatible only with [CLI v3](https://support.crowdin.com/cli-tool-v3/). Try to use CLI v3

**Comment by dfdgsdfg** [comment]
I removed brew installed Crowdin CLI, then install a new version.

```bash
$ java -jar ~/bin/crowdin-cli.jar lint
Your configuration file looks good

$java -jar ~/bin/crowdin-cli.jar list project
❌ Fetching project info     
❌ Failed to collect project info. Please contact our support team for help
❌ Project with id 'effy-app' doesn't exist
```

Is it related with my project id? It has a hyphen in the project name.

<img width="670" alt="스크린샷 2020-04-13 오후 4 37 33" src="https://user-images.githubusercontent.com/474775/79102184-2f02a600-7da5-11ea-889f-6862ecdf8291.png">

**Comment by andrii-bodnar** [comment]
The project identifier is using only for CLI v2. 

For CLI v3 and Configuration file v3 you should use numerical project ID:

![screenshot-crowdin com-2020 04 13-10_42_09](https://user-images.githubusercontent.com/29282228/79102491-8425c400-7d73-11ea-99c9-2d9f952a31f9.png)

**Comment by dfdgsdfg** [comment]
Seems connect project without error. 

How can I use this plugin?

It shows a project, but doesn't contain anything. I clicked the refresh icon and download icon, but nothing happened.

<img width="198" alt="스크린샷 2020-04-13 오후 4 53 25" src="https://user-images.githubusercontent.com/474775/79103448-8bff5b80-7da7-11ea-8383-732629adb6de.png">

**Comment by andrii-bodnar** [comment]
The plugin will build tree with source files. In Crowdin Explorer you can upload those files into Crowdin and download translations.

Please check the files section in `crowdin.yml` and make sure that patterns respond to localization files structure in your project.

**Comment by dfdgsdfg** [comment]
@alexandrtovmach Thanks. I will try it.
