### ISSUE TITLE
please add support to flags in crowdin.yaml

### ISSUE THREAD

**Issue by wwojcik** [crowdin/vscode-crowdin#23]
please add suport to flags 
```
project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_API_TOKEN"
```

**Comment by Olena1234** [comment]
Hi @wwojcik ! Could you please provide more details on your request?

**Comment by andrii-bodnar** [comment]
Hi @wwojcik, thank you for the suggestion!
We will consider adding this feature in the nearest release.

**Comment by wwojcik** [comment]
thx

**Comment by andrii-bodnar** [comment]
PR #24
