### ISSUE TITLE
 Config, update_option

### ISSUE THREAD

**Issue by hendrik-stjernstrom** [crowdin/vscode-crowdin#33]
Hi! First of all great job with this makes my life easier as a developer.

Would it be possible to be able to keep existing strings when i upload my source file.
From the configuration file it would be:

 "update_option": "update_without_changes"

We use the original translation in the source file and for that reason it would be nice to not have to retranslate the translations for minor changes. I do understand the reason for this to be default though.

Keep up the great work!

**Comment by andrii-bodnar** [comment]
Hi @hendrik-stjernstrom!

Thanks a lot for the feedback provided, this feature totally makes sense in the Crowdin Visual Studio Code Plugin, we will implement it in the nearest release :+1:

**Comment by andrii-bodnar** [comment]
Hi @hendrik-stjernstrom!
This feature is already available in the [1.0.7](https://github.com/crowdin/vscode-crowdin/releases/tag/1.0.7) version.
