### ISSUE TITLE
Images are corrupted when uploading

### ISSUE THREAD

**Issue by Epicpkmn11** [crowdin/vscode-crowdin#42]
**Describe the bug**
When uploading an image using the VS Code plugin it becomes corrupted. Examining the image in a hex editor it appears to be replacing all bytes that are invalid ASCII with `EF BF BD` (UTF-8 for �, U+FFFD) so it seems they're being parsed as ASCII text at some point. This doesn't happen if I upload directly using the website.

**To Reproduce**
1. Upload an image
2. Try to view the image online or download it

**Expected behavior**
Images are uploaded correctly.

**Environment (please complete the following information):**
 - OS: macOS
 - VS Code version: 1.55.2

**Additional context**
Source file: https://github.com/Epicpkmn11/TWiLightMenu/raw/translatable-images/romsel_dsimenutheme/nitrofiles/languages/en/photo_default.png
After upload: [photo_default.png](https://user-images.githubusercontent.com/41608708/114706172-45ac4780-9cee-11eb-89ee-15ef04095fc2.png)
Crowdin project: https://crowdin.com/project/TwilightMenu (Note: I've already reuploaded the image from the website)

**Comment by yevheniyJ** [comment]
@Epicpkmn11 Fixed in v1.1.1
