### ISSUE TITLE
Add support for split project configuration and API credentials

### ISSUE THREAD

**Issue by silopolis** [crowdin/vscode-crowdin#57]
As recommended in https://support.crowdin.com/configuration-file/#split-project-configuration-and-api-credentials

Extension doesn't seem to support reading split sensitive informations from `.crowdin.[yml|yaml]` aside of the default file for project configuration.

It'd be great so we can place this private file at the root directory of VCS managed project and add it to the ignored files list so it is not pushed to public repositories.

Thanks in advance
TY

**Comment by OlenaKot** [comment]
Hi @silopolis !

We will check whether it is possible and will come back to you as soon as possible

Meanwhile, wishing you a lovely day

**Comment by andrii-bodnar** [comment]
Hi @silopolis !
Configuration splitting is not supported by the Crowdin VS Code plugin, but there is a possibility to use environment variables. Did you consider this option?

**Comment by silopolis** [comment]
I usually favor config files over env vars for many reasons. But indeed I can fallback to these...
Thanks for your quick answer 👍
